version: "3.1"
services:
  ruby: 
    image: hichamajarif/ruby-rails-2.7.5
    container_name: rails-web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"